application: ookong001
version: 8
runtime: python
api_version: 1

builtins:
- remote_api: on
- datastore_admin: on

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- Makefile
